kind: pipeline
type: docker
name: default

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    restore: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - name: node_local_repo
        path: /cache

  # node打包
  - name: build
    image: daixk1212/node
    volumes:
      - name: node_local_repo
        path: /wwwroot
    commands:
      - node -v
      - yarn -v
      - yarn config set cache-folder .yarn-cache
      - yarn config set registry http://registry.npm.taobao.org/
      - yarn config set sass_binary_site https://npm.taobao.org/mirrors/node-sass
      - yarn
      - npm run build:stage

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    rebuild: true
    mount:
      - ./.yarn-cache
      - ./node_modules
    volumes:
      - name: node_local_repo
        path: /cache

  # dist部署
#  - name: deploy
#    image: appleboy/drone-scp
#    settings:
#      host:
#        from_secret: ssh_host
#      port: 22
#      username: root
#      key:
#        from_secret: ssh_key
#      target:
#        from_secret: deploy_path
#      source: ./dist/*
#    when:
#      status:
#        - success



#  # 钉钉通知
#  - name: dingtalk
#    image: lddsb/drone-dingtalk-message
#    settings:
#      token:
#        from_secret: dingtalk_token
#      type: markdown
#      tpl: ./markdown.tpl
#      tips_title: 新的构建已完成，请测试
#      message_color: true
#      success_color: 39D839
#      failure_color: E93939
#      tpl_build_status_success: passed
#      tpl_buaild_status_failure: failed
#      sha_link: true
#    when:
#      status: [failure, success]

volumes:
  - name: node_local_repo
    host:
      path: /data/node
