kind: pipeline
type: docker
name: default

steps:
  # node打包
  - name: build
    image: registry.cn-hangzhou.aliyuncs.com/hbhb/node
    volumes:
      - name: node_local_repo
        path: /wwwroot
    commands:
      - node -v
      - yarn -v
      - yarn config set registry http://registry.npm.taobao.org/
      - yarn
      - npm run build:stage

  # dist部署
#  - name: deploy
#    image: appleboy/drone-scp
#    settings:
#      host:
#        from_secret: ssh_host
#      port: 22
#      username: root
#      key:
#        from_secret: ssh_key
#      target:
#        from_secret: deploy_path
#      source: ./dist/*
#    when:
#      status:
#        - success



#  # 钉钉通知
#  - name: dingtalk
#    image: lddsb/drone-dingtalk-message
#    settings:
#      token:
#        from_secret: dingtalk_token
#      type: markdown
#      tpl: ./markdown.tpl
#      tips_title: 新的构建已完成，请测试
#      message_color: true
#      success_color: 39D839
#      failure_color: E93939
#      tpl_build_status_success: passed
#      tpl_buaild_status_failure: failed
#      sha_link: true
#    when:
#      status: [failure, success]

volumes:
  - name: node_local_repo
    host:
      path: /data/node
