kind: pipeline
type: docker
name: default

steps:
  # 使用缓存
  - name: restore-cache
    image: drillster/drone-volume-cache
    settings:
      restore: true
      mount:
        - ./node_modules
    volumes:
      - name: node_cache
        path: /cache

  # 打包
  - name: build
    image: node:alpine
    commands:
      - node -v
      - yarn -v
      - yarn config set registry http://registry.npm.taobao.org/
      - yarn config set sass_binary_site https://npm.taobao.org/mirrors/node-sass
      - yarn run build:prod

  # 更新缓存
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./node_modules
    volumes:
      - name: node_cache
        path: /cache

  # 部署
  - name: deploy
    image: appleboy/drone-scp
    settings:
      host:
        from_secret: ssh_host
      port: 22
      username: root
      key:
        from_secret: ssh_key
      target: /app/zhcw/prod
      source: dist/*
      rm: true
      strip_components: 1
    when:
      status:
        - success

  # 钉钉通知
  - name: dingtalk
    image: lddsb/drone-dingtalk-message
    settings:
      token:
        from_secret: dingtalk_token
      type: markdown
      tpl: ./markdown.tpl
      tips_title: 新的构建已完成，请测试
      message_color: true
      success_color: 39D839
      failure_color: E93939
      tpl_build_status_success: passed
      tpl_buaild_status_failure: failed
      sha_link: true
    when:
      status: [failure, success]

volumes:
  - name: node_cache
    host:
      path: /data/node
